### ISSUE TITLE
Forced new line after #version?

### ISSUE THREAD

**Issue by Ciel-MC** [walt-grace/glsl-plugin-idea#10]
![image](https://user-images.githubusercontent.com/47144701/198836713-4acbc2aa-65ec-4afc-a7f9-5512a8f3b4f6.png)
![image](https://user-images.githubusercontent.com/47144701/198836707-6fc29932-a81c-47b0-a3a8-a9517fdfb8e7.png)
An error was reported if there's no newline at the end of #version
I don't think this is intended. probably just a missing `?` in the grammar file.

**Comment by walt-grace** [comment]
This is intended. A preprocessor must finish with a new line.

**Comment by Ciel-MC** [comment]
> This is intended. A preprocessor must finish with a new line. 

Okay, thank you.
