### ISSUE TITLE
Support 223.*

### ISSUE THREAD

**Issue by xiaozhuai** [walt-grace/glsl-plugin-idea#13]
Jetbrains' ide has upgrade to 223. Please support it.

**Comment by cchulo** [comment]
If I'm reading this correctly, isn't it just a matter of opening a PR and bumping this [up](https://github.com/walt-grace/glsl-plugin-idea/blob/ec3c9994be0ebc6bbd186db33463d22683edc786/build.gradle#L68)?

**Comment by xiaozhuai** [comment]
> If I'm reading this correctly, isn't it just a matter of opening a PR and bumping this [up](https://github.com/walt-grace/glsl-plugin-idea/blob/ec3c9994be0ebc6bbd186db33463d22683edc786/build.gradle#L68)?

This should be it.

**Comment by cchulo** [comment]
https://github.com/walt-grace/glsl-plugin-idea/pull/14

**Comment by walt-grace** [comment]
@cchulo 
As mentioned here 
https://github.com/walt-grace/glsl-plugin-idea/issues/11#issuecomment-1350209598
I can't find the time to fix the other issue and the version thing should basically be bumped up regardless of that. So either I will just find the time in the next days to only bump up the version and run the tests successfully or we can reopen your PR. But then you'll have to figure out why the tests didn't pass (and of course feel free to ask anything you don't understand or need clarification).

**Comment by cchulo** [comment]
@walt-grace I should have sometime coming up in the next week due to holiday, I can look into this again then :)
