### ISSUE TITLE
suggestion: More color style options

### ISSUE THREAD

**Issue by alphaqu** [walt-grace/glsl-plugin-idea#16]
It would be great if the plugin allowed for deeper syntax highlighting.

## Expand user defined identifiers
Currently nearly everything falls under the "User defined identifier" which is quite limiting, it would be great if it had different attribute for different identifiers.

- Locals
- Changed locals (locals which have been reassigned)
- Parameters
- Changed parameters
### Specific globals
- `layout` value
- `uniform` value
- `in` value
- `out` value
- `struct` value
- `buffer` value
### Fields
- `struct` Fields
- `buffer` Fields

## Builtin types
Builtin types should have a separate attribute for functions and fields as those are quite different.

## Operators
It would be great if the plugin allows color styling of braces and operators like semi-colon, braces, brackets, comma, dot, operator sign, parentheses, semicolon etc.

**Comment by walt-grace** [comment]
Hi @alphaqu 
Thanks for suggestion and sorry for the late replay. There are bunch of things and I think this would easy to solve. 

* _Locals_:  By locals I assume you mean local variable right? If yes, good idea. Will be implement. 
* _Changed locals_: These are a bit more tricky as they need processing, i.e. to actually check if the variable has been reassigned. This piece of information doesn't exist by default so new logic needs to be written. I find this also a cool idea. 
* _Parameters_: As far as I can see, this is working (default brownish color).
* _Changed parameters_: Same as with changed locals.

Specific globals:
Not sure I agree about that, as keywords should have in my opinion a uniform color. And breaking this logic will make the code (of the plugin) uglier. If more people would like to have that, then I'll go implement that. Same for _struct_ and _buffer_ as they are also keywords.

Builtin types
Not sure I get this point. Can you provide an example? 

Operators
Sure why not. To be honest I already implement it once but then I though that no would ever need that haha. 

So I'm trying these days to go back to the project. Hope to have some progress this week.

**Comment by alphaqu** [comment]
What i mean by specific globals is that the struct name needs to be able to be different from something like a uniform. And attributes should be able to have a custom color to easily differiate between uniforms and attributes.

Built-in types currently all have the same color. Something like `gl_Position` (a field) has the same color as a function like `blend`. I think you should be able to have a unique color for both of these values.

**Comment by walt-grace** [comment]
Alright got it. I already did the operators. These were the easiest. I will have a look at uniforms and attributes.

**Comment by abbator** [comment]
One option we don't have is to change the color of braces/parentheses/delimiters. I tend to make these a little bit darker than the default white as I find it more readable.

**Comment by walt-grace** [comment]
@alphaqu can I close the ticket? Seems to work on my end.
