### ISSUE TITLE
#include does not work

### ISSUE THREAD

**Issue by alphaqu** [walt-grace/glsl-plugin-idea#17]
The plugin fails to resolve most cases of `#include` and "Find usages" does not work at all on things defined in a different file. I'm also having an exception thrown by the plugin saying psi elements are overflowing a short.

**Comment by walt-grace** [comment]
Hi @alphaqu 
Can you please supply more details?

**Comment by walt-grace** [comment]
I would then close the ticket if it's good now.

**Comment by alphaqu** [comment]
```glsl
#version 100

#include "file_one.glsl"

void main() {
	thing();
}
```
file two
```glsl
#version 100

void thing() {

}
```

**Comment by walt-grace** [comment]
Are these 2 files in the same directory?

**Comment by alphaqu** [comment]
> Are these 2 files in the same directory?

Yes

**Comment by walt-grace** [comment]
The next release should a full support for macros (also for #define). It's pretty complicated so it's taking some time. The problem is that I did changes to the grammar in such a way that I have to either release the whole thing or none. Stay in tune :)
