### ISSUE TITLE
Vector indexing error

### ISSUE THREAD

**Issue by bishan-batel** [walt-grace/glsl-plugin-idea#19]
The plugin shows an error when trying to index into a vector with an int.
![vector_index](https://user-images.githubusercontent.com/45645805/222847018-7296ce60-6a11-49e9-bd51-c7cdec4d0b0c.png)

**Comment by walt-grace** [comment]
@bishan-batel 
Thanks for you input. I try to find time to do some stuff here. There are also few other issues. Hopefully soon :)

**Comment by walt-grace** [comment]
This should be fixed with release 1.0.7. Looks all good on your side?

**Comment by bishan-batel** [comment]
It works on my side, thank you!
