### ISSUE TITLE
imageLoad/Store missing image2D overloads?

### ISSUE THREAD

**Issue by coffeenotfound** [walt-grace/glsl-plugin-idea#2]
It seems that currently the image* function overloads for image2D are missing including `imageLoad(image2D, ivec2)` and `imageStore(image2D, ivec2, vec4)`

Some other functions like `imageSize(image2D)` do exist on the otherhand

**Comment by walt-grace** [comment]
Bloody overloading. There are around 2000 different signatures for all builtin functions. I missed some of them. Will be added to next release.
