### ISSUE TITLE
Compatiblity with PS 2023.1

### ISSUE THREAD

**Issue by uuf6429** [walt-grace/glsl-plugin-idea#20]
I don't know enough about the plugin code, but is there anything really incompatible with the latest IDE version?
If not, maybe the following line should be patched (with `231.*`) and the plugin re-released?

https://github.com/walt-grace/glsl-plugin-idea/blob/4f07f074a09aad798c7cd1b5a8a05b0ff5ca56a1/build.gradle#L67

PS: I've had the pleasure to use the plugin for a couple of days, so looking forward to seeing it work again!

**Comment by walt-grace** [comment]
@uuf6429  
I'm closing the ticket if it all looks good.
