### ISSUE TITLE
Add support for interface blocks

### ISSUE THREAD

**Issue by tomheaton** [walt-grace/glsl-plugin-idea#24]
Add support for interface blocks (https://www.khronos.org/opengl/wiki/Interface_Block_(GLSL)), allowing you to access the `TextureCoords` definition by clicking on `IN.TextureCoords`.

This would be a great addition to the plugin!

```frag
#version 330 core

uniform sampler2D Texture;

in VS_OUTPUT {
    vec3 Color;
    vec2 TextureCoords;
} IN;

out vec4 Color;

void main() {
    Color = texture(Texture, IN.TextureCoords);
}

```

**Comment by walt-grace** [comment]
To be honest I'm pretty surprised that it doesn't work. It definitely should. I'll have a look.
