### ISSUE TITLE
Add support to silence errors

### ISSUE THREAD

**Issue by aggregate1166877** [walt-grace/glsl-plugin-idea#25]
I'm using [Three.js](https://threejs.org/), which supplies a lot of uniforms to the ShaderMaterial without the need to manually import them.

For example, I have written this code:
```
vec4 mvPosition = vec4(position, 1.0);
```

`vec4` is underlined and I get the error "Too few arguments to constructor of 'vec4'." `position` is a `vec3` so this code is valid.

I don't expect the plugin to understand custom libraries, so it might make sense to allow error suppression. Maybe something like:
```
// @ignore - Too few arguments
vec4 mvPosition = vec4(position, 1.0);
```

Would it be possible to add something like this is to suppress errors?

**Comment by walt-grace** [comment]
I disabled the code annotations altogether as there way too many errors.

**Comment by aggregate1166877** [comment]
I mean, it was manageable. Just needed something similar to `// @ts-ignore` to kill the worst offenders
