### ISSUE TITLE
Support for 2023.2

### ISSUE THREAD

**Issue by natehitze** [walt-grace/glsl-plugin-idea#26]
First - thanks for this plugin, it's been really helpful.

The error:
> Plugin 'GLSL' (version '1.0.71') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is RD-232.8660.212

I think this PR would make the necessary version update: https://github.com/walt-grace/glsl-plugin-idea/pull/23

**Comment by cchulo** [comment]
has this project been abandoned?

**Comment by walt-grace** [comment]
Was released today
