### ISSUE TITLE
Add separate plugin for CLion Nova

### ISSUE THREAD

**Issue by cchulo** [walt-grace/glsl-plugin-idea#28]
A new version of CLion is on the horizon

Upon loading it up I found that the current plugin does not work, am wondering if either it can be updated to support Nova or maybe have a separate experimental plugin available for it.

**Comment by rachit7645** [comment]
Could you check if PR #29 makes it work?

**Comment by hiradyazdan** [comment]
Is there any update on this yet?

**Comment by rachit7645** [comment]
Nope. This repository's owner has been inactive since 26 of September last year.

**Comment by cchulo** [comment]
temp solution is to build the plugin and install manually

**Comment by walt-grace** [comment]
Guys never forgot you. Going to do it next days.

**Comment by walt-grace** [comment]
Is it all good now guys?
