### ISSUE TITLE
IDE is showing a Problem PP_END expected, got 'version'

### ISSUE THREAD

**Issue by LolBaum** [walt-grace/glsl-plugin-idea#33]
Plugin version: 1.0.74
IDE: CLion

My IDE marks the first line of my glsl shaders `# version 330` as problem with the message 
> PP_END expected, got 'version'

complete file

``` glsl
# version 330
layout(location = 0) in vec3 a_position;
layout(location = 1) in vec2 a_texture;

uniform vec2 iResolution;

out vec2 fragCoord;

void main()
{
    gl_Position = vec4(a_position, 1.0);
    fragCoord = (a_position.xy+1)/2*iResolution;
}
```

This is not a big deal, but a bit annoying. The code is working fine.

**Comment by walt-grace** [comment]
Because it should be #version, without space. It's important.

**Comment by LolBaum** [comment]
Why is this important? as far as I know the whitespace is ok (at least in versions >= 330, I didn't use older versions).
Is it generally definded in the standard that there musst be no whitespace between `#` and `version`? Or is it for compatibility reasons important?

**Comment by walt-grace** [comment]
I'm not sure about the MUST thing, but in any case I follow exactly the GLSL spec. 
![image](https://github.com/walt-grace/glsl-plugin-idea/assets/73055476/5242e58d-b153-487e-a4a7-5aaf277086db)

Why is that a problem? Why not to write the preprocessor as it's always written?

**Comment by LolBaum** [comment]
Well that's convention is a good Point.
I was just curious about if the reason was actually related to GLSL, because my code compiled correctly.
Thanks for the clarification.

**Comment by walt-grace** [comment]
I'm kinda surprised that it complies and worked, but on the other hand why not? The compiler can figure out you meant define.
