### ISSUE TITLE
Syntax Highlighting for GLSL Embedded in HTML

### ISSUE THREAD

**Issue by andonagio** [walt-grace/glsl-plugin-idea#34]
I work with a lot of GLSL that looks like this:

```
<script id="vshader" type="x-shader/x-vertex">
    precision mediump float;

    attribute vec4 vPosition;
    uniform mat4 cameraMatrix;
    uniform mat4 projMatrix;
    uniform mat4 modelMatrix;

    void main() {
        gl_Position = projMatrix * cameraMatrix * modelMatrix * vPosition;
    }
</script>
```

Is it possible to use the plugin to get GLSL syntax highlighting on the embedded code? Because the code file itself is HTML, the IDEA applications use that syntax highlighting, which means the GLSL between the script tags isn't highlighted at all. None of the language injection options seem to work, either.

I'd like to find a solution that doesn't involve putting the GLSL in a string or moving it to a separate file.

**Comment by walt-grace** [comment]
Hi @andonagio 
I'll try to find time of doing. This should not be too complicated.

**Comment by andonagio** [comment]
That would be fantastic! Thank you!

**Comment by walt-grace** [comment]
Hi @andonagio 
Can you provide me with more details about what framework you are using? Is it WebGL?
In other words, I need to find a condition when to fire the language injection (embedding) since I don't want to inject it to any <script> ta. Maybe with the id or the type attribute, but can you provide more details for under which conditions the plugin should be inject to the string.

**Comment by walt-grace** [comment]
I think the best condition would be any <script> tag that have a "type" attribute that contains "x-shader". 
What do you think about that?

**Comment by andonagio** [comment]
That should work. I usually only work with type="x-shader/x-vertex" for my vertex shander and type="x-shader/x-fragment" for my fragment shader. (Are there others? I don't know.) I would imagine any block with a "type" attribute containing "x-shader" is probably dealing with GLSL.

**Comment by walt-grace** [comment]
@andonagio it's released. If everything works as expected, we can close the ticket.

**Comment by andonagio** [comment]
Thank you! I just updated the plugin, and it looks good! Go ahead and close it out.
