### ISSUE TITLE
Add .vsh, .gsh, .fsh as file extension

### ISSUE THREAD

**Issue by Bixilon** [walt-grace/glsl-plugin-idea#4]
Actually I am searching in the code (wanted to contribute it), how to add these aliases, but I can not find it.

I am naming my shaders with `.vsh` for vertex shaders, `.gsh` for geometry shaders or `.fsh` for fragment shaders.

Can you add those aliases by default or tell me where I can add then (in the code, not in IntelliJ  Idea)?

Moritz

**Comment by walt-grace** [comment]
I will add it to next release. 
In general, the extensions are listed in plugin.xml.

**Comment by walt-grace** [comment]
No need for pull request. I already added it to the code. It's literally adding 3 words.

**Comment by Bixilon** [comment]
Sad, #hacktoberfest
