### ISSUE TITLE
support glsl inside other ext file content

### ISSUE THREAD

**Issue by chen1zee** [walt-grace/glsl-plugin-idea#8]
for example，I am working in aaa.js , writing JavaScript, using three.js.
inside aaa.js , I have part of GLSL code,
for example:
```javascript
const thisIsJs = '123';
const someShaderStr = `
#include <common>
# .... glsl code
`
```
can someShaderStr has GLSL highLight?

**Comment by xiaozhuai** [comment]
Jetbrains' already already contains a feature called `language injection`
[Use language injection comments](https://www.jetbrains.com/help/idea/using-language-injections.html#use-language-injection-comments)

<img width="429" alt="image" src="https://user-images.githubusercontent.com/4773701/199152831-d63878f6-f9f2-47c0-a9bb-f98d3f2cc49b.png">

**Comment by walt-grace** [comment]
@chen1zee sorry for the late reply. 
Seems like @xiaozhuai found a pretty elegant solution for that that I wasn't aware of. Hope that'll work for you. 
thank you @xiaozhuai!
